alias be 'bundle exec'
alias browse 'hub browse'
alias c 'calc -d'
alias e 'emacsclient -nw -c'
alias g 'git'
alias ip 'dig +short myip.opendns.com @resolver1.opendns.com'
alias l 'ls'
alias l. 'ls -d .*'
alias ll 'ls -l'
alias m 'mplayer'
alias t 'tree'
