# Also read Intel HID events so Makima can track the Copilot combo if some
# modifier events are emitted on this companion device on the X1 Carbon.

[remap]
KEY_LEFTSHIFT-KEY_LEFTMETA-KEY_F23 = ["KEY_RIGHTCTRL"]

[settings]
GRAB_DEVICE = "true"
