# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
windowrule = workspace 1, match:class chromium

# Pin Emacs to workspace 2
windowrule = workspace 2, match:class emacs

# Pin Reflect and ChatGPT to workspace 3
windowrule = workspace 3, match:class chrome-reflect.app__-Default
windowrule = workspace 3, match:class chrome-chatgpt.com__-Default

# Pin Feedbin to workspace 4
windowrule = workspace 4, match:class chrome-feedbin.com__-Default

# Pin Spotify to workspace 5
windowrule = workspace 5, match:class spotify

# Pin Signal and Discord as a group on workspace 6
windowrule = workspace 6, match:class signal
windowrule = group set, match:class signal
windowrule = workspace 6, match:class chrome-discord.com__channels_@me-Default
windowrule = group set, match:class chrome-discord.com__channels_@me-Default

# Pin Typora to workspace 9
windowrule = workspace 9, match:class Typora

# Pin 1Password to scratchpad
windowrule = workspace special:scratchpad, match:class 1password
windowrule = center on, match:class 1password
