{ lib, outOfStore, ... }:

{
  imports = [ ./maintenance.nix ];

  # Host-specific user config for the museum exe.dev VM (museum.exe.xyz), a
  # headless Ubuntu 24.04 machine for cloud agent development on the Museum
  # project. It imports only nix/home-manager/core.nix; provisioning and
  # machine-local glue (login shell, ~/.config/fish/local.fish, the exe.dev
  # env file) live in script/exe-setup.sh in the museum repo.
  #
  # Secrets and pairing state are out of band, like the Rails master.key:
  # ~/.pi/agent/auth.json, Herdr runtime state, fish_variables.

  # The laptops sign with a 1Password-held key via op-ssh-sign-wrapper (see
  # common/git.nix); neither exists on the VM. Instead the VM signs with a
  # dedicated, signing-only ed25519 key generated by script/exe-setup.sh in
  # the museum repo and registered on GitHub as a *signing* key (it cannot
  # authenticate). The path form lets ssh-keygen find the private half next
  # to it, so agents and detached Herdr sessions can sign unattended. The
  # public half is also listed in common/git.nix's allowed_signers. Ubuntu's
  # ssh-keygen does the signing, matching the system git this profile uses.
  programs.git.signing = {
    key = lib.mkForce "~/.ssh/id_ed25519_signing.pub";
    signer = lib.mkForce "/usr/bin/ssh-keygen";
  };

  # The exeuntu image's exe-dev extension is relocated to ~/.pi/exe-dev by
  # script/exe-setup.sh. Keep that extra path in a host-specific, writable
  # settings file without imposing the laptops' saved model preferences.
  home.file.".pi/agent/settings.json".source = lib.mkForce
    (outOfStore "nix/hosts/museum/pi-settings.json");
}
